config/routes.rb
Rails.application.routes.draw do
  get 'doses/new'
  get 'doses/create'
  get 'doses/destroy'
  get 'cocktails/index'
  get 'cocktails/show'
  get 'cocktails/new'
  get 'cocktails/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true, uniqueness: { scope: :ingredient_id }
  validates :ingredient_id, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: %i[new create]

  def new
    @ingredients = Ingredient.all
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save == true
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.input :name %>
    <%= f.button :submit, class: "btn btn-primary"%>
  </div>
<% end %>

app/views/cocktails/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "Cocktails", cocktails_path, class: "navbar-brand" %>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<%= render 'navbar', cocktail: @cocktail %>

<ul>
  <% @cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail %></li>
  <% end %>
</ul>

<%= link_to 'Add a new cocktail', cocktails_new_path %>

<div class="homeGrid__item  homeGrid__item--0    homeGrid__item--small" data-colorhome="#04a0c5">
  <a class="homeGrid__product" href="https://shop.antoinecorbineau.com/products/ile-dyeu/">
  <img src="https://shop.antoinecorbineau.com/wp-content/uploads/iledyeu_1200-1000x687.png">
  <div class="homeGrid__sticker" style="background-color:;color:">
    <div>
    </div>
  </div>
  </a>
  <div class="homeGrid__hover">
    <svg class="svg" width="458" height="799" viewBox="0 0 458 799" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 275v524h458V0c-31.156116 16.800674-74.822783 29.800674-131 39-84.265826 13.798989-120.366108 138.435504-185 143-43.0892615 3.042997-90.4225948 34.042997-142 93z" fill="#04a0c5" fill-rule="evenodd"/>
    </svg>
    <div>
      <div>Île d&#8217;Yeu</div>
      <div>
        <span class="woocommerce-Price-amount amount">30,00
          <span class="woocommerce-Price-currencySymbol">&euro;</span>
        </span>
      </div>
    </div>
    <div>Discover</div>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
<%= f.input :name %>
<%= f.submit %>

<% end %>
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<ul>
  <% ingredients =  @cocktail.ingredients %>
  <% ingredients.each do |ingredient| %>
  <li><%= ingredient.name %></li>
  <% end %>
</ul>


<% doses = @cocktail.doses %>
<% doses.each do|dose| %>
  <div>
    <h4><%= dose.ingredient.name %></h4>
    <h4><%= dose.description %></h4>
    <img src='<%= dose.ingredient.image_url %>' alt="">
  </div>
<% end %>

<%= link_to 'Back', cocktails_path %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<div class="container">
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :description, as: :text %>
  <%= f.association :ingredient%>
  <%= f.submit "add a dose", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>